language: node_js
node_js:
- 4.2 
branches:
  only:
  - master
  - test
before_install:
  - openssl aes-256-cbc -K $encrypted_f88d79a9e3f2_key -iv $encrypted_f88d79a9e3f2_iv -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - eval $(ssh-agent)
  - ssh-add ~/.ssh/id_rsa
  - cp .travis/ssh_config ~/.ssh/config
  - mkdir temp_lxc
  - cd temp_lxc
  - npm install hexo-deployer-git --save
install:
  - npm install -g hexo-cli
  - npm install hexo --save
  - hexo init
before_script:
  - cp -R ../source ./
  - cp -R ../themes ./
  - cp ../_config.yml ./
  - git config --global user.name 'lixingcong'
  - git config --global user.email 'lixingcong@live.com'
script:
  - hexo clean
  - hexo d -g
